version: "3"
services:
  shard1:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - ./shard1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  shard2:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5435:5432"
    volumes:
      - ./shard2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  shard3:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "35432:5432"
    volumes:
      - ./shard3:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: some@mail.com
    restart: unless-stopped
    volumes:
      - ./pgadmin:/var/lib/pgadmin4/storage

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - shard1
      - shard2
      - shard3
    container_name: node-app
    restart: always
    volumes:
      - $PWD:/usr/src/app
      - /usr/src/app/node_modules

